### PR TITLE
Revert "Try to fix android-headers pc file"

### PR DESCRIPTION
**Pull request by JamiKettunen**
This breaks `make install` :(

This reverts commit 4cc8c2c169b77aaee6142f417d2a710c48507f3c.

@NotKit @Herrie82 Is there a reason for this commit? I don't think this hack makes any sense here if it's here just to make some debian packaging work.

### CODE REVIEW

**Comment by JamiKettunen** [comment]
Marking as a draft for now so we can discuss what the proper fix is.

Another solution would be to replace https://github.com/Halium/android-headers/blob/halium-11.0/Makefile#L12 with https://github.com/Halium/android-headers/blob/halium-9.0/Makefile#L11-L12 so it matches what 9.0 has as well.

**Comment by Herrie82** [comment]
The issue I'm having is that I'm building the headers using Yocto using the following recipe. We explicitly skip the Makefile by the looks of it, which all works fine with 5.1/7.0/9.0 but not with 11.00 headers.

https://github.com/shr-distribution/meta-smartphone/blob/master/meta-android/recipes-android/android-headers/android-headers.inc

Hence I came up with the commit that you're having issues with.

**Comment by JamiKettunen** [comment]
> The issue I'm having is that I'm building the headers using Yocto using the following recipe. We explicitly skip the Makefile by the looks of it, which all works fine with 5.1/7.0/9.0 but not with 11.00 headers.

Right, so everything there is done manually without invoking the Makefile (but why? is there something wrong with all the Makefiles? perhaps they should be fixed here if that's the case; never used Yocto so I don't know if their packaging supports a `post_install()` function for example that could still be used to do fixups specific to Yocto)

@Herrie82 Would the suggestion from [my previous comment](https://github.com/Halium/android-headers/pull/4#issuecomment-1111265028) be fine?

**Comment by Herrie82** [comment]
Well this seems to work OK at my end when reverting the commit: https://github.com/shr-distribution/meta-smartphone/pull/143

**Comment by Herrie82** [comment]
> 

Not sure, I inherited this from other devs, I don't know why they did it this way to start with to be honest ;)

**Comment by Herrie82** [comment]
If you want I can hard reset the branch to commit 2c6ac3dcc4f8db593dd69906b0ec22822abfed91 so we lose the noise?

**Comment by JamiKettunen** [comment]
@Herrie82 I suppose I'm fine with that.

**Comment by Herrie82** [comment]
@NotKit You're OK with going back to 2c6ac3dcc4f8db593dd69906b0ec22822abfed91 ?

**Comment by NotKit** [comment]
@Herrie82 fine for me

**Comment by Herrie82** [comment]
Hard reset the 11.0 headers now. We should be good.

**Pull request closed without merging**
